<?php
/**
 * Thin PHP wrapper for the 404 page.
 * Serves the static 404.html generated by Eleventy with a proper
 * HTTP 404 status so search engines don't index missing pages.
 */

http_response_code(404);

$html = file_get_contents(__DIR__ . '/404.html');

if ($html === false) {
    exit('Not Found');
}

echo $html;
